USE [master]
GO

/****** Object:  Database [_Schedule]    Script Date: 12/26/2014 8:06:26 PM ******/
CREATE DATABASE [_Schedule] ON  PRIMARY 
( NAME = N'_Schedule', FILENAME = N'J:\SERVER_DATA1\_Schedule.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'_Schedule_log', FILENAME = N'K:\SERVER_LOG1\_Schedule_log.LDF' , SIZE = 576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [_Schedule] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [_Schedule].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [_Schedule] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [_Schedule] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [_Schedule] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [_Schedule] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [_Schedule] SET ARITHABORT OFF 
GO

ALTER DATABASE [_Schedule] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [_Schedule] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [_Schedule] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [_Schedule] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [_Schedule] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [_Schedule] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [_Schedule] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [_Schedule] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [_Schedule] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [_Schedule] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [_Schedule] SET  ENABLE_BROKER 
GO

ALTER DATABASE [_Schedule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [_Schedule] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [_Schedule] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [_Schedule] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [_Schedule] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [_Schedule] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [_Schedule] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [_Schedule] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [_Schedule] SET  MULTI_USER 
GO

ALTER DATABASE [_Schedule] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [_Schedule] SET DB_CHAINING OFF 
GO

ALTER DATABASE [_Schedule] SET  READ_WRITE 
GO


