USE [master]
GO

/****** Object:  Database [Schedule]    Script Date: 12/26/2014 8:06:49 PM ******/
CREATE DATABASE [Schedule] ON  PRIMARY 
( NAME = N'Schedule', FILENAME = N'J:\SERVER_DATA1\Schedule.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Schedule_log', FILENAME = N'K:\SERVER_LOG1\Schedule_log.LDF' , SIZE = 832KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Schedule] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Schedule].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Schedule] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Schedule] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Schedule] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Schedule] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Schedule] SET ARITHABORT OFF 
GO

ALTER DATABASE [Schedule] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Schedule] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Schedule] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Schedule] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Schedule] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Schedule] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Schedule] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Schedule] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Schedule] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Schedule] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Schedule] SET  ENABLE_BROKER 
GO

ALTER DATABASE [Schedule] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Schedule] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Schedule] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Schedule] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Schedule] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Schedule] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Schedule] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Schedule] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Schedule] SET  MULTI_USER 
GO

ALTER DATABASE [Schedule] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Schedule] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Schedule] SET  READ_WRITE 
GO


